cargo-features = ["named-profiles", "profile-overrides"]

[workspace]
members = [
  "core",
  "client",
  "server",
]
default-members = [
  "core",
  "client",
  "server",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
publish = false

[workspace.dependencies]
tokio = "1"
futures = "0.3"
crates_io_api = "0.8"
chrono = "0.4"
serde = "1"
serde_json = "1"
thiserror = "1"
tracing = "0.1"
tracing-subscriber = "0.3"
directories = "5"
