[package]
name = "att_server"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
att_core = { path = "../core" }
axum = "0.6"
tokio = { version = "1", features = ["rt-multi-thread", "time", "macros", "signal"] }
futures = "0.3"
crates_io_api = "0.8"
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
directories = "5"
thiserror = "1"
tracing = "0.1"
tracing-subscriber = "0.3"
