[package]
name = "iced_builder"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
iced = { workspace = true, default-features = true, features = ["advanced"] }
